<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace Moodle\Composer\Plugin\Scaffold\Scaffolding\Generator;

use Composer\Util\Filesystem;

/**
 * Moodle Config File Generator.
 */
class ConfigFile extends BaseGenerator
{
    /**
     * {@inheritDoc}
     */
    #[\Override]
    public function generate(): void
    {
        $this->io->write('Generating Moodle configuration file...');

        // Get the vendor directory.
        $vendorPath = $this->getVendorPath();
        $targetPath = $this->getMoodlePath() . '/config.php';

        $relativePath = $this->calculateRelativePath(
            $targetPath,
            dirname($vendorPath) . '/config.php',
        );

        file_put_contents($targetPath, $this->getTemplateContent($relativePath));
    }

    protected function getTemplateContent(string $relativePathToRoot): string
    {
        $vendorPath = $this->getVendorPath();
        return <<<TEMPLATE
        <?php

        /**
         * Include the Moodle configuration file for a Composer-based Moodle installation.
         *
         * This file was automatically generated by the Moodle Composer Scaffold plugin.
         *
         * Do NOT edit this file manually. It will be overridden on the next scaffolding operation.
         */
        \$result = require_once(__DIR__ . '/{$relativePathToRoot}');
        require_once('{$vendorPath}/autoload.php');
        require_once(__DIR__ . '/public/lib/setup.php');

        return \$result;
        TEMPLATE;
    }
}
