<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace Moodle\Composer\Scaffold\Scaffolding\Generator;

use Composer\Util\Filesystem;

/**
 * Moodle Config File Generator.
 */
class ShimBinMoodleFile extends BaseGenerator
{
    /**
     * {@inheritDoc}
     */
    #[\Override]
    public function generate(): void
    {
        $this->io->write("- <info>Shimming Moodle Console Tool...</info>", false);

        $targetPath = $this->getRootPackagePath() . '/msh';

        file_put_contents($targetPath, $this->getTemplateContent());
        chmod($targetPath, 0755);

        $this->io->write("<info> done.</info>");
    }

    protected function getTemplateContent(): string
    {
        $moodleDir = $this->getInstallDirectory();

        return <<<TEMPLATE
        #!/usr/bin/env php
        <?php

        /**
         * Include the Moodle configuration file for a Composer-based Moodle installation.
         *
         * This file was automatically generated by the Moodle Composer Scaffold plugin.
         *
         * Do NOT edit this file manually. It will be overridden on the next scaffolding operation.
         */

        return include __DIR__ . '/{$moodleDir}bin/moodle';

        TEMPLATE;
    }
}
